// <auto-generated />
namespace GarbageCollection.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addedpickupsmodelcontrollerandviews : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedpickupsmodelcontrollerandviews));
        
        string IMigrationMetadata.Id
        {
            get { return "201807311844293_Added pickups model, controller and views."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
